[package]
name = "ngdl_rust"
version = "0.1.0"
authors = ["Fabian Richardt <f.richardt@t-online.de>"]
edition = "2018"

[dependencies]
gnuplot = "0.0.32"
itertools = "0.8.0"
rayon = "1.2.0"
nalgebra = "0.18.1"
derive-new = "0.5.8"